// Auto-generated — do not edit manually. Run `bun run generate-registry` to update.

export interface ProjectMeta {
  slug: string;
  title: string;
  shortDescription: string;
  techStack: string[];
  links: { type: string; url: string }[];
  image: string;
  logo?: string;
  date: string;
}

export const projectMetadata: Record<string, ProjectMeta> = {
  'arduino-nodejs': {"title":"Arduino NodeJs","shortDescription":"IoT web controller bridging Node.js with Arduino via serial communication.","techStack":["nextjs","nodejs","express","react"],"links":[{"type":"github","url":"https://github.com/souhailcodes/arduino-nodejs.git"}],"image":"/images/arduino.webp","date":"Jan 2023","slug":"arduino-nodejs"},
  'berrypoints': {"title":"BerryPoints","shortDescription":"Reward-based advertising platform where users earn money by completing offers.","techStack":["nextjs","nestjs","typescript","tailwindcss","mongodb","docker"],"links":[{"type":"website","url":"https://berrypoints.com"}],"image":"/images/berrypoints.webp","logo":"/images/berrypoints-logo.ico","date":"Oct 2025","slug":"berrypoints"},
  'bestshape': {"title":"BestShape","shortDescription":"Personalized fitness program generator in 30 seconds via a multi-step questionnaire.","techStack":["nextjs","typescript","tailwindcss","mongodb","shadcn"],"links":[{"type":"website","url":"https://best-shape-alpha.vercel.app/"},{"type":"github","url":"https://github.com/souhailcodes/BestShape"},{"type":"youtube","url":"https://youtu.be/XZBETa-s_mY"}],"image":"/images/bestshape.png","logo":"/images/bestshape-logo.ico","date":"Feb 2024","slug":"bestshape"},
  'brand-name-generator': {"title":"Brand Name Generator","shortDescription":"AI-powered brand name generator using fine-tuned GPT-3.5 with domain and social handle checking.","techStack":["nextjs","typescript","tailwindcss","shadcn","framer-motion"],"links":[{"type":"website","url":"https://brand-name-generator.vercel.app/"}],"image":"/images/domain-name-generator.png","date":"Sep 2023","slug":"brand-name-generator"},
  'clipzr': {"title":"Clipzr","shortDescription":"Windows screen recorder with smooth cursor movements.","techStack":["nestjs","shadcn"],"links":[{"type":"website","url":"https://clipzr.com"}],"image":"/images/clipzr.png","date":"Mar 2026","logo":"/images/clipzr-logo.png","slug":"clipzr"},
  'comsep': {"title":"Comsep","shortDescription":"AI-powered domain name generator with real-time WHOIS availability checking.","techStack":["nextjs","typescript","tailwindcss","mongodb","nextauth","shadcn"],"links":[{"type":"website","url":"https://domain-name-generator-iota.vercel.app/"}],"image":"/images/comsep.png","logo":"/images/comsep-logo.png","date":"Nov 2024","slug":"comsep"},
  'cpa-analytics': {"title":"CPA Analytics","shortDescription":"Full-stack CPA marketing analytics platform to track visitor behavior on landing pages.","techStack":["nextjs","react","nodejs","express","mongodb","tailwindcss"],"links":[{"type":"github","url":"https://github.com/souhailcodes/cpa-analytics"}],"image":"/images/cpa-analytics.png","date":"Dec 2021","slug":"cpa-analytics"},
  'cpadominator': {"title":"CPADominator","shortDescription":"Full-stack SaaS for creating content-locked landing pages used in CPA/affiliate marketing.","techStack":["nextjs","typescript","tailwindcss","mongodb"],"links":[],"image":"/images/ftdominator.jpg","date":"Mar 2022","slug":"cpadominator"},
  'cpavid': {"title":"CPAVid","shortDescription":"Automated YouTube video creation and uploading system using Remotion and Puppeteer.","techStack":["nextjs","nestjs","typescript","tailwindcss","tauri","rust","mongodb","shadcn"],"links":[],"image":"/images/cpavid.png","date":"Sep 2024","slug":"cpavid"},
  'dailyhabit': {"title":"DailyHabit","shortDescription":"Habit tracker app, runs 100% client-side","techStack":["nextjs","shadcn","tailwindcss","rxdb","motion","lottie"],"links":[{"type":"github","url":"https://github.com/souhailcodes/daily-habit"},{"type":"youtube","url":"https://youtu.be/U6cd310jHC8"},{"type":"website","url":"https://daily-habit-umber.vercel.app/"}],"image":"/images/dailyhabit.png","logo":"/images/dailyhabit-logo.png","date":"May 2026","slug":"dailyhabit"},
  'dofus-marchand-bot': {"title":"Dofus Marchand Bot","shortDescription":"Desktop automation bot for Dofus using OpenCV template matching to automate merchant mode.","techStack":["javascript"],"links":[{"type":"github","url":"https://github.com/souhailcodes/dofus-marchand-bot.git"}],"image":"/images/dofus.jpg","date":"Jul 2022","slug":"dofus-marchand-bot"},
  'eagle-browser': {"title":"Eagle Browser","shortDescription":"RESTful API for managing browser profiles with proxy, fingerprint, and data directory configuration.","techStack":["nodejs","express","mongodb"],"links":[{"type":"github","url":"https://github.com/souhailcodes/eagle-browser"}],"image":"/images/eagle-browser.webp","date":"Mar 2023","slug":"eagle-browser"},
  'edumation': {"title":"Edumation","shortDescription":"AI-powered educational assistant platform for students and educators.","techStack":["nextjs","nodejs","express","react"],"links":[],"image":"/images/edumation.png","date":"Mai 2024","slug":"edumation"},
  'era-js': {"title":"Era.js","shortDescription":"Opinionated Node.js backend framework and CLI tool for scaffolding Express-based REST APIs.","techStack":["nodejs","express","mongodb"],"links":[{"type":"github","url":"https://github.com/souhailcodes/era.js"}],"image":"/images/erajs.png","date":"Jun 2022","slug":"era-js"},
  'fingerprint-js': {"title":"Fingerprint JS","shortDescription":"Client-side browser fingerprinting library generating unique device IDs from 18 browser signals.","techStack":["javascript"],"links":[{"type":"github","url":"https://github.com/souhailcodes/fingerprint-id-jsFile.git"}],"image":"/images/fingerprint.png","date":"Feb 2022","slug":"fingerprint-js"},
  'fox-wallpapers': {"title":"Fox Wallpapers","shortDescription":"Windows Live Wallpaper Engine built using Tauri (React + Rust).","techStack":["tauri","react","rust"],"links":[{"type":"website","url":"https://apps.microsoft.com/detail/9n7r9zf4vsx7"}],"image":"/images/fox-wallpapers.jpeg","logo":"/images/fox-wallpapers-logo.png","date":"Mar 2025","slug":"fox-wallpapers"},
  'framist': {"title":"Framist","shortDescription":"Rapid prototyping tool to create interactive, native-feeling app prototypes in minutes without code.","techStack":["nextjs","react","typescript"],"links":[{"type":"website","url":"https://framist.vercel.app/"},{"type":"youtube","url":"https://www.youtube.com/watch?v=7BpU-hzctqw"}],"image":"/images/framist.png","logo":"/images/framist-logo.png","date":"Jan 2025","slug":"framist"},
  'kolors': {"title":"Kolors","shortDescription":"Color palette generator for design systems with primitive shades and semantic mappings.","techStack":["nextjs","react","typescript","tailwindcss","zustand","shadcn","motion"],"links":[{"type":"website","url":"https://www.kolors.dev/"},{"type":"github","url":"https://github.com/souhailcodes/colors.git"}],"image":"/images/kolors.png","logo":"/images/kolors-logo.png","date":"Dec 2025","slug":"kolors"},
  'lme': {"title":"LME","shortDescription":"Full-stack CMS for a university research laboratory with admin dashboard.","techStack":["react","nodejs","express","mongodb","tailwindcss"],"links":[],"image":"/images/cms.jpg","date":"Dec 2021","slug":"lme"},
  'modifio': {"title":"Modifio","shortDescription":"Client-side file converter powered by FFmpeg WASM.","techStack":["nextjs","typescript","tailwindcss","shadcn","ffmpeg","wasm"],"links":[{"type":"website","url":"https://modifio.vercel.app/"},{"type":"github","url":"https://github.com/souhailcodes/modifio"},{"type":"youtube","url":"https://youtu.be/ypYw6Cm6cUk"}],"image":"/images/modifio.png","logo":"/images/modifio-logo.svg","date":"Sep 2023","slug":"modifio"},
  'nest-cloaker': {"title":"Nest Cloaker","shortDescription":"Affiliate marketing URL cloaking API with device fingerprinting and network filtering.","techStack":["nestjs","typescript","mongodb"],"links":[{"type":"github","url":"https://github.com/souhailcodes/nest-cloaker.git"}],"image":"/images/nest-cloaker.webp","date":"Apr 2023","slug":"nest-cloaker"},
  'next-saas-landing-page': {"title":"NextJs SaaS Landing Page","shortDescription":"Free saas landing page built using next.js, tailwind and framer-motion (100/100 Lightouse score).","techStack":["nextjs","typescript","tailwindcss","shadcn","motion"],"links":[{"type":"website","url":"https://next-saas-lp.vercel.app/"},{"type":"github","url":"https://github.com/souhailcodes/next-saas-lp"}],"image":"/images/next-saas-lp.png","logo":"/images/nextjs-logo.webp","date":"Mar 2025","slug":"next-saas-landing-page"},
  'nextjs-tailwind-portfolio': {"title":"NextJs Tailwind Portfolio","shortDescription":"Personal dark-themed portfolio with Lottie animations, glassmorphism, and Tailwind CSS.","techStack":["nextjs","typescript","tailwindcss","lottie"],"links":[{"type":"github","url":"https://github.com/souhailcodes/nextjs-tailwind-portfolio"},{"type":"youtube","url":"https://www.youtube.com/watch?v=NGpZcR6dfr8"}],"image":"/images/next-portfolio.png","date":"Sep 2023","slug":"nextjs-tailwind-portfolio"},
  'one-page-ecommerce': {"title":"One-page e-commerce","shortDescription":"Single-page e-commerce storefront with WhatsApp ordering for a Moroccan business.","techStack":["nextjs","typescript","tailwindcss"],"links":[{"type":"github","url":"https://github.com/souhailcodes/onepage-ecommerce-shop.git"},{"type":"youtube","url":"https://youtu.be/1HzFYpmx_zs"}],"image":"/images/onepage-ecommerce.png","date":"Apr 2023","slug":"one-page-ecommerce"},
  'pizzaslice': {"title":"PizzaSlice","shortDescription":"ProductHunt for indie game developers. Browse, filter, and discover indie games through video previews.","techStack":["nextjs","typescript","tailwindcss","mongodb","framer-motion"],"links":[{"type":"website","url":"https://pizzaslice-zeta.vercel.app/"}],"image":"/images/pizzaslice.png","logo":"/images/pizzaslice-logo.png","date":"Jan 2025","slug":"pizzaslice"},
  'quotex-auto-trader': {"title":"Quotex Auto Trader","shortDescription":"Chrome extension to automate trading actions on the Quotex platform.","techStack":["html","css","javascript"],"links":[{"type":"github","url":"https://github.com/souhailcodes/quotex_auto_trader"}],"image":"/images/quotex.webp","date":"Oct 2021","slug":"quotex-auto-trader"},
  'randomcall': {"title":"RandomCall","shortDescription":"Full-stack random 1-on-1 video chat app like Omegle/Chatroulette with WebSocket matchmaking.","techStack":["nextjs","nestjs","typescript","tailwindcss","shadcn","docker","redis"],"links":[{"type":"github","url":"https://github.com/souhailcodes/randomcall.git"},{"type":"youtube","url":"https://youtu.be/FamZMfLIYag"}],"image":"/images/randomcall.jpg","date":"Apr 2024","slug":"randomcall"},
  'react-node-auth': {"title":"React Node Auth","shortDescription":"Full-stack MERN authentication app with Passport.js local strategy, session-based auth, and a React frontend.","techStack":["react","nodejs","express","passport","mongodb","mongoose","bcrypt","nodemon"],"links":[{"type":"github","url":"https://github.com/souhailcodes/React-nodeJs-auth-app"}],"image":"/images/passport.jpg","date":"Nov 2021","slug":"react-node-auth"},
  'root-ui-v1': {"title":"Root UI v1 (React-aria)","shortDescription":"React component library built on top of React Aria & TailwindCSS.","techStack":["nextjs","shadcn","tailwindcss","storybook"],"links":[{"type":"website","url":"https://rootui-website.vercel.app/"}],"image":"/images/root-ui-v1.png","logo":"/images/root-ui-v1-logo.png","date":"Jan 2026","slug":"root-ui-v1"},
  'root-ui': {"title":"Root UI v2 (Shadcn)","shortDescription":"Premium Shadcn Components, Blocks and Themes.","techStack":["nextjs","shadcn","tailwindcss","storybook"],"links":[{"type":"website","url":"https://root-ui.com"}],"image":"/images/root-ui.png","logo":"/images/root-ui-logo.png","date":"Apr 2026","slug":"root-ui"},
  'youtube-cheater': {"title":"YouTube Views Bot","shortDescription":"Node.js bot that automates fake YouTube video views using Puppeteer with stealth techniques.","techStack":["javascript","nodejs"],"links":[{"type":"github","url":"https://github.com/souhailcodes/youtube-cheater"}],"image":"/images/youtube-bot.png","date":"Mar 2022","slug":"youtube-cheater"},
}
